---
language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: 'ZQAac2Td8hLKUoO6LOEm9IoGlELOlpCCdaa9tcyZGl/7IOx9+T17kf6cW7FS
      i1DAbG2jT/GUlKgJDnbVahceDlpHG50nUhyYlTo+p2gNCRLn5s2odkmd8dq3
      KEzD5WyUOs0e13Wvq4g8PO8vFRGF8sgbGBhJ6fwHzkmiu4rN2G0='
